---
provisioner:
  name: salt_solo
  formula: docker
  salt_version: "2014.7.5"
  salt_bootstrap_url: "https://raw.githubusercontent.com/saltstack/salt-bootstrap/6080a18e6c7c2d49335978fa69fa63645b45bc2a/bootstrap-salt.sh"
  salt_install: "bootstrap"
  vendor_path: "vendor/_root" 
  salt_file_root: "/srv/salt"
  state_top:
    base:
      '*':
        - docker
  omnibus_cachier: true



platforms:
  - name: vagrant-ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      pre_create_command: "salt-shaker --verbose --root_dir vendor/ install"
      vagrantfile_erb: "kitchenvagrant/Vagrantfile.erb"
      cachier:
        scope: "box"
      customize:
        memory: 1024
      box: "hashicorp/precise64"
      box_url: "https://vagrantcloud.com/hashicorp/boxes/precise64"

  - name: vagrant-ubuntu-14.04
    driver_plugin: vagrant
    driver_config:
      vagrantfile_erb: "kitchenvagrant/Vagrantfile.erb"
      cachier:
        scope: "box"
      customize:
        memory: 1024
      box: "ubuntu/trusty64"
      box_url: "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"


suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - docker
        docker.sls:
          docker:
            datadir: "/home/docker"
